version: '3.8'
services:
  newsletter-bot:
    build: .
    env_file: .env
    volumes:
      - .:/app
    restart: always

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=securepassword
      - N8N_HOST=localhost
      - N8N_PORT=5678
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:




#  How to use (uncommet when using) for n8n workflow setup online:

#  Copy the above file.
# // Go to n8n → Workflows → Import.
#  Paste/upload the JSON file.
#  Configure credentials for Supabase, Gemini, and Mailjet nodes.
# Add/expand with web scraping nodes (HTTP Request + HTML Extract, or Puppeteer) for non-RSS sources.


