services:
  newsletter-bot:
    build: .
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/app
    command: ["python3", "main.py"]

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  dashboard:
    build: .
    env_file: .env
    depends_on:
      - db
    command: ["streamlit", "run", "dashboard.py"]
    ports:
      - "8501:8501"

volumes:
  pgdata: